language: python

python:
  - "3.5"
  - "3.4"
  - "2.7"
  - "pypy"
  - "pypy3"

env:
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
  
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=1.9
    - python: "3.3"
      env: DJANGO=1.10

# command to install dependencies
install:
    - pip install tox-travis

# command to run tests
script:
    - tox
